//go:build linux

package linkforge

import (
	"errors"
	"fmt"
	"io/fs"
	"net"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

const defaultDNSPath = "/etc/resolv.conf"

type managedDNSFile struct {
	original []byte
	existed  bool
	mode     fs.FileMode
	owners   map[string][]net.IP
}

func dnsPath(cfg DHCPConfig) string {
	if !cfg.WriteDNS {
		return ""
	}
	if cfg.DNSPath == "" {
		return defaultDNSPath
	}
	return filepath.Clean(cfg.DNSPath)
}

func (c *Client) setSessionDNS(owner, path string, servers []net.IP) error {
	if path == "" {
		return nil
	}

	c.dnsMu.Lock()
	defer c.dnsMu.Unlock()
	state := c.dnsFiles[path]
	if state == nil {
		var err error
		state, err = readManagedDNSFile(path)
		if err != nil {
			return err
		}
	}

	owners := cloneDNSOwners(state.owners)
	owners[owner] = cloneIPs(servers)
	if err := writeDNSFile(path, combinedDNS(owners)); err != nil {
		return err
	}
	state.owners = owners
	c.dnsFiles[path] = state
	return nil
}

func (c *Client) removeSessionDNS(owner, path string) error {
	if path == "" {
		return nil
	}

	c.dnsMu.Lock()
	defer c.dnsMu.Unlock()
	state := c.dnsFiles[path]
	if state == nil {
		return nil
	}
	owners := cloneDNSOwners(state.owners)
	delete(owners, owner)
	if len(owners) > 0 {
		if err := writeDNSFile(path, combinedDNS(owners)); err != nil {
			return err
		}
		state.owners = owners
		return nil
	}

	if err := restoreDNSFile(path, state); err != nil {
		return err
	}
	delete(c.dnsFiles, path)
	return nil
}

func readManagedDNSFile(path string) (*managedDNSFile, error) {
	state := &managedDNSFile{
		mode:   0o644,
		owners: make(map[string][]net.IP),
	}
	info, err := os.Stat(path)
	if errors.Is(err, os.ErrNotExist) {
		return state, nil
	}
	if err != nil {
		return nil, fmt.Errorf("stat DNS file %q: %w", path, err)
	}
	if !info.Mode().IsRegular() {
		return nil, fmt.Errorf("DNS path %q is not a regular file", path)
	}
	contents, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("read DNS file %q: %w", path, err)
	}
	state.original = contents
	state.existed = true
	state.mode = info.Mode().Perm()
	return state, nil
}

func writeDNSFile(path string, servers []net.IP) error {
	var contents strings.Builder
	contents.WriteString("# Generated by linkforge. Changes will be overwritten.\n")
	for _, server := range servers {
		if server == nil || server.To16() == nil {
			continue
		}
		contents.WriteString("nameserver ")
		contents.WriteString(server.String())
		contents.WriteByte('\n')
	}
	if err := os.WriteFile(path, []byte(contents.String()), 0o644); err != nil {
		return fmt.Errorf("write DNS file %q: %w", path, err)
	}
	return nil
}

func restoreDNSFile(path string, state *managedDNSFile) error {
	if !state.existed {
		if err := os.Remove(path); err != nil && !errors.Is(err, os.ErrNotExist) {
			return fmt.Errorf("remove managed DNS file %q: %w", path, err)
		}
		return nil
	}
	if err := os.WriteFile(path, state.original, state.mode); err != nil {
		return fmt.Errorf("restore DNS file %q: %w", path, err)
	}
	return nil
}

func cloneDNSOwners(input map[string][]net.IP) map[string][]net.IP {
	result := make(map[string][]net.IP, len(input))
	for owner, servers := range input {
		result[owner] = cloneIPs(servers)
	}
	return result
}

func combinedDNS(owners map[string][]net.IP) []net.IP {
	keys := make([]string, 0, len(owners))
	for owner := range owners {
		keys = append(keys, owner)
	}
	sort.Strings(keys)
	groups := make([][]net.IP, 0, len(keys))
	for _, owner := range keys {
		groups = append(groups, owners[owner])
	}
	return mergeIPs(groups...)
}
